services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: hirehub-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hirehub.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    networks:
      - hirehub-net

  app:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: hirehub-app
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - hirehub-net
    command: >
      sh -c "mvn -q -DskipTests package && java -jar target/*.jar"

volumes:
  postgres_data:

networks:
  hirehub-net: