version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hirehub-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hirehub-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: hirehub-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hirehub.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - hirehub-net

  app:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: hirehub-app
    working_dir: /app
    command: sh -c "mvn -q -DskipTests package && java -jar target/*.jar"
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - hirehub-net

volumes:
  postgres_data:

networks:
  hirehub-net:
